AWSTemplateFormatVersion: '2010-09-09'
Description: A CloudFormation template to deploy the Stable Diffusion Web UI by Automatic1111

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: sd-webui-sg
      GroupDescription: Security group for whisper-demo EC2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 7860
          ToPort: 7860
          CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: g4dn.xlarge
      ImageId: ami-0574da719dca65348
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 300
            VolumeType: gp2
      "Tags" : [
            {"Key" : "Name", "Value" : "sd-web-ui-cf"},
        ]
      SecurityGroups:
        - Ref: SecurityGroup
      UserData:
        'Fn::Base64': |
            #!/bin/bash
            cd /home/ubuntu
            git clone https://github.com/marshmellow77/stable-diffusion-webui.git
            bash stable-diffusion-webui/setup.sh -y
          

#            sudo sed -i "/#\$nrconf{restart} = 'i';/s/.*/\$nrconf{restart} = 'a';/" /etc/needrestart/needrestart.conf
#            sudo apt-get update
#            sudo apt install wget git python3 python3-venv build-essential
#
#            # install CUDA (from https://developer.nvidia.com/cuda-downloads)
#            wget https://developer.download.nvidia.com/compute/cuda/12.0.0/local_installers/cuda_12.0.0_525.60.13_linux.run
#            sudo sh cuda_12.0.0_525.60.13_linux.run --silent
#
#            git clone https://github.com/marshmellow77/stable-diffusion-webui.git
#
#            # install git-lfs
#            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
#            sudo apt-get install git-lfs
#            git lfs install --skip-smudge
#
#            git clone --depth 1 https://huggingface.co/stabilityai/stable-diffusion-2-1-base
#            cd stable-diffusion-2-1-base/
#            git lfs pull --include "v2-1_512-ema-pruned.ckpt"
#            cd ..
#            mv stable-diffusion-2-1-base/v2-1_512-ema-pruned.ckpt stable-diffusion-webui/models/Stable-diffusion/
#            wget https://raw.githubusercontent.com/Stability-AI/stablediffusion/main/configs/stable-diffusion/v2-inference.yaml
#            cp v2-inference.yaml stable-diffusion-webui/models/Stable-diffusion/v2-1_512-ema-pruned.yaml
#            cd stable-diffusion-webui/
#
#            bash webui-setup.sh

  MyEIP:
    Type: AWS::EC2::EIP

  MyEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt MyEIP.AllocationId
      InstanceId: !Ref EC2Instance